//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Partlyx.UI.Avalonia.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Partlyx.UI.Avalonia.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occured during opening a file. File wasn&apos;t opened.
        /// </summary>
        internal static string An_error_occured_during_opening_a_file_File_wasnt_opened {
            get {
                return ResourceManager.GetString("An_error_occured_during_opening_a_file_File_wasnt_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occured during saving a file. File wasn&apos;t saved.
        /// </summary>
        internal static string An_error_occured_during_saving_a_file_File_wasnt_saved {
            get {
                return ResourceManager.GetString("An_error_occured_during_saving_a_file_File_wasnt_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear search text.
        /// </summary>
        internal static string Clear_search_text {
            get {
                return ResourceManager.GetString("Clear_search_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collapse all.
        /// </summary>
        internal static string Collapse_All {
            get {
                return ResourceManager.GetString("Collapse_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collapse branch.
        /// </summary>
        internal static string Collapse_branch {
            get {
                return ResourceManager.GetString("Collapse_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Component.
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Component {0}.
        /// </summary>
        internal static string Component_N {
            get {
                return ResourceManager.GetString("Component_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a component for this recipe.
        /// </summary>
        internal static string Create_a_component_for_this_recipe {
            get {
                return ResourceManager.GetString("Create_a_component_for_this_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a recipe for this resource.
        /// </summary>
        internal static string Create_a_recipe_for_this_resource {
            get {
                return ResourceManager.GetString("Create_a_recipe_for_this_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a resource.
        /// </summary>
        internal static string Create_resource {
            get {
                return ResourceManager.GetString("Create_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default recipe.
        /// </summary>
        internal static string Default_recipe {
            get {
                return ResourceManager.GetString("Default_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details:.
        /// </summary>
        internal static string Details_ {
            get {
                return ResourceManager.GetString("Details_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to save your file before creating a new one?.
        /// </summary>
        internal static string Do_you_want_to_save_your_file_before_creating_a_new_one_ {
            get {
                return ResourceManager.GetString("Do_you_want_to_save_your_file_before_creating_a_new_one_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to save your file before leaving?.
        /// </summary>
        internal static string Do_you_want_to_save_your_file_before_leaving_ {
            get {
                return ResourceManager.GetString("Do_you_want_to_save_your_file_before_leaving_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to save your file before creating a new one?.
        /// </summary>
        internal static string Do_you_want_to_save_your_file_before_opening_another_one {
            get {
                return ResourceManager.GetString("Do_you_want_to_save_your_file_before_opening_another_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expand all.
        /// </summary>
        internal static string Expand_All {
            get {
                return ResourceManager.GetString("Expand_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expand branch.
        /// </summary>
        internal static string Expand_branch {
            get {
                return ResourceManager.GetString("Expand_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partree files.
        /// </summary>
        internal static string filter_Partree_files {
            get {
                return ResourceManager.GetString("filter_Partree_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find in tree.
        /// </summary>
        internal static string Find_in_tree {
            get {
                return ResourceManager.GetString("Find_in_tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find setted resource in tree.
        /// </summary>
        internal static string Find_setted_resource_in_tree {
            get {
                return ResourceManager.GetString("Find_setted_resource_in_tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid file error.
        /// </summary>
        internal static string Invalid_file_error {
            get {
                return ResourceManager.GetString("Invalid_file_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string menu_Edit {
            get {
                return ResourceManager.GetString("menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Needed amount.
        /// </summary>
        internal static string Needed_amount {
            get {
                return ResourceManager.GetString("Needed_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in editor.
        /// </summary>
        internal static string Open_in_editor {
            get {
                return ResourceManager.GetString("Open_in_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Project (.partree).
        /// </summary>
        internal static string partree_Open_Project {
            get {
                return ResourceManager.GetString("partree_Open_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Project (.partree).
        /// </summary>
        internal static string partree_Save_Project {
            get {
                return ResourceManager.GetString("partree_Save_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parts tree.
        /// </summary>
        internal static string Parts_Tree {
            get {
                return ResourceManager.GetString("Parts_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на funny programm for interesting things.
        /// </summary>
        internal static string postfix_funny_programm_for_interesting_things {
            get {
                return ResourceManager.GetString("postfix_funny_programm_for_interesting_things", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send my regards to David :D.
        /// </summary>
        internal static string postfix_Send_my_regards_to_David___ {
            get {
                return ResourceManager.GetString("postfix_Send_my_regards_to_David___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на you forgot to save &lt;:(.
        /// </summary>
        internal static string postfix_you_forgot_to_save {
            get {
                return ResourceManager.GetString("postfix_you_forgot_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product amount.
        /// </summary>
        internal static string Product_amount {
            get {
                return ResourceManager.GetString("Product_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recipe.
        /// </summary>
        internal static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;{0}&quot; {1} component.
        /// </summary>
        internal static string recipe_component_properties_annotation {
            get {
                return ResourceManager.GetString("recipe_component_properties_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recipe {0}.
        /// </summary>
        internal static string Recipe_N {
            get {
                return ResourceManager.GetString("Recipe_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;{0}&quot; recipe.
        /// </summary>
        internal static string recipe_properties_annotation {
            get {
                return ResourceManager.GetString("recipe_properties_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource.
        /// </summary>
        internal static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource {0}.
        /// </summary>
        internal static string Resource_N {
            get {
                return ResourceManager.GetString("Resource_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;{0}&quot; resource.
        /// </summary>
        internal static string resource_properties_annotation {
            get {
                return ResourceManager.GetString("resource_properties_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return to the tree root.
        /// </summary>
        internal static string Return_to_the_tree_root {
            get {
                return ResourceManager.GetString("Return_to_the_tree_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as....
        /// </summary>
        internal static string Save_as___ {
            get {
                return ResourceManager.GetString("Save_as___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving error.
        /// </summary>
        internal static string Saving_error {
            get {
                return ResourceManager.GetString("Saving_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search....
        /// </summary>
        internal static string Search___ {
            get {
                return ResourceManager.GetString("Search___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected recipe.
        /// </summary>
        internal static string Selected_recipe {
            get {
                return ResourceManager.GetString("Selected_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set as default.
        /// </summary>
        internal static string Set_as_default {
            get {
                return ResourceManager.GetString("Set_as_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The button that does the weird thing.
        /// </summary>
        internal static string The_button_that_does_the_weird_thing {
            get {
                return ResourceManager.GetString("The_button_that_does_the_weird_thing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This file is not saved.
        /// </summary>
        internal static string The_file_is_not_saved {
            get {
                return ResourceManager.GetString("The_file_is_not_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle focus.
        /// </summary>
        internal static string Toggle_focus {
            get {
                return ResourceManager.GetString("Toggle_focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total recipe&apos;s resources amount.
        /// </summary>
        internal static string Total_resources_amount {
            get {
                return ResourceManager.GetString("Total_resources_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoom in.
        /// </summary>
        internal static string Zoom_in {
            get {
                return ResourceManager.GetString("Zoom_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoom out.
        /// </summary>
        internal static string Zoom_out {
            get {
                return ResourceManager.GetString("Zoom_out", resourceCulture);
            }
        }
    }
}
