// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Partlyx.Infrastructure.Data;

#nullable disable

namespace Partlyx.Infrastructure.Migrations.PartlyxDB
{
    [DbContext(typeof(PartlyxDBContext))]
    [Migration("20260101113839_RecipesIndependanceMigration")]
    partial class RecipesIndependanceMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Partlyx.Core.Partlyx.Recipe", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnType("BLOB")
                        .HasColumnName("Uid");

                    b.Property<string>("IconData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IconType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReversible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("Partlyx.Core.Partlyx.RecipeComponent", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnType("BLOB")
                        .HasColumnName("Uid");

                    b.Property<Guid>("ComponentResourceUid")
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("ComponentSelectedRecipeUid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOutput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("RecipeUid")
                        .HasColumnType("BLOB");

                    b.HasKey("Uid");

                    b.HasIndex("ComponentResourceUid");

                    b.HasIndex("RecipeUid");

                    b.ToTable("RecipeComponents", (string)null);
                });

            modelBuilder.Entity("Partlyx.Core.Partlyx.Resource", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB")
                        .HasColumnName("Uid");

                    b.Property<Guid?>("DefaultRecipeUid")
                        .HasColumnType("BLOB");

                    b.Property<string>("IconData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IconType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Partlyx.Core.PartlyxImage", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("CompressedContent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.HasIndex("Hash");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("Partlyx.Core.Partlyx.RecipeComponent", b =>
                {
                    b.HasOne("Partlyx.Core.Partlyx.Resource", "ComponentResource")
                        .WithMany()
                        .HasForeignKey("ComponentResourceUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Partlyx.Core.Partlyx.Recipe", "ParentRecipe")
                        .WithMany("Components")
                        .HasForeignKey("RecipeUid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ComponentResource");

                    b.Navigation("ParentRecipe");
                });

            modelBuilder.Entity("Partlyx.Core.Partlyx.Recipe", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
