// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Partlyx.Infrastructure.Data;

#nullable disable

namespace Partlyx.Infrastructure.Migrations
{
    [DbContext(typeof(PartlyxDBContext))]
    partial class PartlyxDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Partlyx.Core.Recipe", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnType("BLOB")
                        .HasColumnName("Uid");

                    b.Property<double>("CraftAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("IconData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IconType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceUid")
                        .HasColumnType("BLOB");

                    b.HasKey("Uid");

                    b.HasIndex("ResourceUid");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("Partlyx.Core.RecipeComponent", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnType("BLOB")
                        .HasColumnName("Uid");

                    b.Property<Guid>("ComponentResourceUid")
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("ComponentSelectedRecipeUid")
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("RecipeUid")
                        .HasColumnType("BLOB");

                    b.HasKey("Uid");

                    b.HasIndex("ComponentResourceUid");

                    b.HasIndex("RecipeUid");

                    b.ToTable("RecipeComponents", (string)null);
                });

            modelBuilder.Entity("Partlyx.Core.Resource", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB")
                        .HasColumnName("Uid");

                    b.Property<Guid?>("DefaultRecipeUid")
                        .HasColumnType("BLOB");

                    b.Property<string>("IconData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IconType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Partlyx.Core.Recipe", b =>
                {
                    b.HasOne("Partlyx.Core.Resource", "ParentResource")
                        .WithMany("Recipes")
                        .HasForeignKey("ResourceUid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentResource");
                });

            modelBuilder.Entity("Partlyx.Core.RecipeComponent", b =>
                {
                    b.HasOne("Partlyx.Core.Resource", "ComponentResource")
                        .WithMany()
                        .HasForeignKey("ComponentResourceUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Partlyx.Core.Recipe", "ParentRecipe")
                        .WithMany("Components")
                        .HasForeignKey("RecipeUid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ComponentResource");

                    b.Navigation("ParentRecipe");
                });

            modelBuilder.Entity("Partlyx.Core.Recipe", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Partlyx.Core.Resource", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
